//
// Copyright 2025 Arkavo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//

import XCTest
import Metal
import simd
@testable import VRMMetalKit

/// First-person head hiding must apply to the inverted-hull outline as well as
/// the surface it traces.
///
/// The body shader degenerates head-weighted vertices in `.firstPerson`, but the
/// dedicated outline pass took no first-person input at all, so the hull of a
/// hidden head was still drawn: a dark shell across the camera. Double-sided
/// materials are exactly what that pass draws (`MToonOutlineDraw.shouldMerge`
/// rejects them), and face and eye items are force-double-sided, so the face is
/// the geometry that hit it.
///
/// The assertions are on rendered pixels, not on pipeline existence: the hidden
/// case must produce an empty frame while the same model with cleared flags
/// still draws, so a regression in either the shader input or the renderer
/// binding fails the test.
final class OutlineFirstPersonHiddenTests: XCTestCase {

    private var device: MTLDevice!
    private static let renderSize = 64
    private static let backgroundColor = MTLClearColor(red: 1, green: 0, blue: 1, alpha: 1)

    override func setUpWithError() throws {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw XCTSkip("Metal device not available (CI without GPU)")
        }
        self.device = device
    }

    override func tearDown() {
        device = nil
    }

    /// Third person is the baseline: hull and surface both draw.
    @MainActor
    func testOutlineDrawsInThirdPerson() throws {
        let painted = try renderPaintedPixels(cameraMode: .thirdPerson, hideVertices: false)
        XCTAssertGreaterThan(painted, 0,
            "Scaffolding invalid: the skinned double-sided outlined triangle drew nothing in third person")
    }

    /// With the head flagged hidden, first person must clear the frame. Before
    /// the fix the surface vanished and the hull remained.
    @MainActor
    func testHiddenVerticesDrawNoOutlineHullInFirstPerson() throws {
        let painted = try renderPaintedPixels(cameraMode: .firstPerson, hideVertices: true)
        XCTAssertEqual(painted, 0,
            "First-person hidden vertices still produced \(painted) painted pixels. The " +
            "surface is degenerated by the body shader, so these are outline hull pixels: " +
            "the dedicated outline pass is ignoring firstPersonHiddenFlags again.")
    }

    /// Control: the camera mode alone must not blank the frame. Without this a
    /// renderer that skipped the outline pass entirely in first person would
    /// pass the test above for the wrong reason.
    @MainActor
    func testVisibleVerticesStillDrawInFirstPerson() throws {
        let painted = try renderPaintedPixels(cameraMode: .firstPerson, hideVertices: false)
        XCTAssertGreaterThan(painted, 0,
            "First person with no hidden vertices drew nothing; the outline pass is being " +
            "skipped by camera mode rather than by the per-vertex flags")
    }

    // MARK: - Render harness

    /// Renders one frame and counts pixels differing from the clear color.
    @MainActor
    private func renderPaintedPixels(cameraMode: VRMRenderer.VRMCameraMode, hideVertices: Bool) throws -> Int {
        let model = try makeSkinnedOutlinedTriangleModel()

        var config = RendererConfig()
        config.sampleCount = 1
        config.strict = .off
        let renderer = VRMRenderer(device: device, config: config)
        renderer.performanceTracker = PerformanceTracker()
        renderer.loadModel(model)

        // After loadModel: the loader recomputes per-vertex hidden flags from the
        // humanoid head bone, which this synthetic model does not have, so the
        // flags must be written over the buffer it installs.
        let primitive = try XCTUnwrap(model.meshes.first?.primitives.first)
        let flags = [UInt8](repeating: hideVertices ? 1 : 0, count: primitive.vertexCount)
        primitive.firstPersonHiddenFlagsBuffer = device.makeBuffer(
            bytes: flags, length: flags.count, options: .storageModeShared)

        renderer.viewMatrix = matrix_identity_float4x4
        renderer.projectionMatrix = matrix_identity_float4x4
        renderer.cameraMode = cameraMode

        let size = Self.renderSize
        let colorDesc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .bgra8Unorm, width: size, height: size, mipmapped: false)
        colorDesc.usage = [.renderTarget, .shaderRead]
        colorDesc.storageMode = .shared
        let depthDesc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .depth32Float, width: size, height: size, mipmapped: false)
        depthDesc.usage = .renderTarget
        depthDesc.storageMode = .private

        guard let colorTex = device.makeTexture(descriptor: colorDesc),
              let depthTex = device.makeTexture(descriptor: depthDesc),
              let queue = device.makeCommandQueue(),
              let commandBuffer = queue.makeCommandBuffer() else {
            throw XCTSkip("Could not allocate Metal render targets")
        }

        let rpd = MTLRenderPassDescriptor()
        rpd.colorAttachments[0].texture = colorTex
        rpd.colorAttachments[0].loadAction = .clear
        rpd.colorAttachments[0].clearColor = Self.backgroundColor
        rpd.colorAttachments[0].storeAction = .store
        rpd.depthAttachment.texture = depthTex
        rpd.depthAttachment.loadAction = .clear
        rpd.depthAttachment.clearDepth = 1.0
        rpd.depthAttachment.storeAction = .dontCare

        renderer.drawOffscreenHeadless(
            to: colorTex, depth: depthTex, commandBuffer: commandBuffer, renderPassDescriptor: rpd)
        commandBuffer.commit()
        commandBuffer.waitUntilCompleted()

        let bytesPerRow = size * 4
        var pixels = [UInt8](repeating: 0, count: bytesPerRow * size)
        pixels.withUnsafeMutableBytes { raw in
            colorTex.getBytes(raw.baseAddress!,
                              bytesPerRow: bytesPerRow,
                              from: MTLRegionMake2D(0, 0, size, size),
                              mipmapLevel: 0)
        }

        // BGRA clear color is (255, 0, 255); anything else was painted by a draw.
        var painted = 0
        for pixel in stride(from: 0, to: pixels.count, by: 4) {
            let isBackground = pixels[pixel] == 255 && pixels[pixel + 1] == 0 && pixels[pixel + 2] == 255
            if !isBackground { painted += 1 }
        }
        return painted
    }

    // MARK: - Fixture

    /// One skinned, double-sided, outlined triangle filling the middle of NDC,
    /// bound to a single identity joint. Double-sided is what routes the hull to
    /// the dedicated outline pass instead of merging it into the body draw.
    private func makeSkinnedOutlinedTriangleModel() throws -> VRMModel {
        let gltfJSON = """
        {"asset":{"version":"2.0"},"scene":0,"scenes":[{"nodes":[0]}],\
        "nodes":[{"name":"root"},{"name":"head"},{"name":"mesh_node"}]}
        """
        let gltf = try JSONDecoder().decode(GLTFDocument.self, from: Data(gltfJSON.utf8))
        let model = VRMModel(
            specVersion: .v1_0,
            meta: VRMMeta(licenseUrl: "https://vrm.dev/licenses/1.0/"),
            humanoid: nil,
            gltf: gltf
        )
        for (index, gltfNode) in (gltf.nodes ?? []).enumerated() {
            model.nodes.append(VRMNode(index: index, gltfNode: gltfNode))
        }
        let nodes = model.nodes
        nodes[1].parent = nodes[0]
        nodes[0].children.append(nodes[1])
        nodes[2].parent = nodes[0]
        nodes[0].children.append(nodes[2])
        nodes[2].mesh = 0
        nodes[2].skin = 0
        nodes[0].updateWorldTransform()

        let skin = VRMSkin(name: "one_joint")
        skin.joints = [nodes[1]]
        skin.inverseBindMatrices = [matrix_identity_float4x4]
        model.skins = [skin]

        let materialJSON = #"{"name":"outlined","doubleSided":true}"#
        let gltfMaterial = try JSONDecoder().decode(GLTFMaterial.self, from: Data(materialJSON.utf8))
        let material = VRMMaterial(from: gltfMaterial, textures: [])
        var mtoon = VRMMToonMaterial()
        // Screen-space width so the hull is unambiguously several pixels wide at
        // 64x64; the world-coordinates hull on a fixture this close to the camera
        // extrudes by a fraction of a pixel and would make the assertions vacuous.
        mtoon.outlineWidthMode = .screenCoordinates
        mtoon.outlineWidthFactor = 6.0
        mtoon.outlineColorFactor = SIMD3<Float>(0, 0, 0)
        material.mtoon = mtoon
        material.doubleSided = true
        model.materials = [material]

        let mesh = VRMMesh(name: "tri")
        let primitive = VRMPrimitive()
        var verts = [VRMVertex(), VRMVertex(), VRMVertex()]
        verts[0].position = SIMD3<Float>(-0.4, -0.4, 0)
        verts[1].position = SIMD3<Float>( 0.4, -0.4, 0)
        verts[2].position = SIMD3<Float>( 0.0,  0.4, 0)
        for index in 0..<3 {
            // Radial normals, not (0,0,1): the hull extrudes along the normal, so a
            // flat triangle facing the camera has a zero-length screen-space normal
            // and produces no hull at all.
            let radial = SIMD3<Float>(verts[index].position.x, verts[index].position.y, 0)
            verts[index].normal = simd_normalize(radial)
            verts[index].texCoord = SIMD2<Float>(0, 0)
            verts[index].color = SIMD4<Float>(1, 1, 1, 1)
            verts[index].joints = SIMD4<UInt32>(0, 0, 0, 0)
            verts[index].weights = SIMD4<Float>(1, 0, 0, 0)
        }
        primitive.uploadVertices(verts, device: device)
        primitive.localMin = SIMD3<Float>(-0.4, -0.4, 0)
        primitive.localMax = SIMD3<Float>( 0.4,  0.4, 0)
        // Clockwise winding: the outline pass culls front faces (the inverted-hull
        // technique), so a counter-clockwise triangle would produce no hull pixels
        // at all and make the assertions vacuous.
        let indices: [UInt16] = [0, 2, 1]
        primitive.indexBuffer = device.makeBuffer(
            bytes: indices, length: 3 * MemoryLayout<UInt16>.stride, options: .storageModeShared)
        primitive.indexCount = 3
        primitive.indexType = .uint16
        primitive.indexBufferOffset = 0
        primitive.primitiveType = .triangle
        primitive.hasNormals = true
        primitive.hasJoints = true
        primitive.hasWeights = true
        primitive.requiredPaletteSize = 1
        primitive.materialIndex = 0
        primitive.vertexCount = 3

        mesh.primitives = [primitive]
        model.meshes = [mesh]
        return model
    }
}
