name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: swift:6.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Check for build warnings
      run: swift build --build-tests 2>&1 | tee build.log && ! grep -i "warning:" build.log
