name: Feature Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    container:
      image: swift:6.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Swift version
      run: swift --version

    - name: Check for merge conflicts
      run: |
        if grep -r "<<<<<<< HEAD" --include="*.swift" --include="*.metal" .; then
          echo "::error::Merge conflict markers found"
          exit 1
        fi

    - name: Check file permissions
      run: |
        find . -name "*.swift" -perm +111 -exec echo "::warning file={}::Swift file should not be executable" \;

    - name: Verify license headers
      run: |
        missing=0
        for file in $(find Sources -type f \( -name "*.swift" -o -name "*.metal" \)); do
          if ! grep -q "Apache License" "$file"; then
            echo "::error file=$file::Missing Apache License header"
            missing=1
          fi
        done
        exit $missing

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Check for build warnings
      run: swift build --build-tests 2>&1 | tee build.log && ! grep -i "warning:" build.log
