name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Build package (release mode)
      run: swift build -c release

    - name: Run tests
      run: swift test

    - name: Create Release Notes
      id: release_notes
      run: |
        if [ -f CHANGELOG.md ]; then
          # Extract release notes for this version from CHANGELOG
          awk "/^## \[${VERSION}\]/{flag=1; next} /^## \[/{flag=0} flag" CHANGELOG.md > release_notes.md
        else
          echo "Release ${VERSION}" > release_notes.md
        fi
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
